# Generated by Django 5.1.5 on 2025-02-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_post_options_news_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_post',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='news_post',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='news_post',
            name='author',
        ),
        migrations.AlterField(
            model_name='news_post',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='Краткое описание новости'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название новости'),
        ),
    ]
